name: nc
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.4
  - matplotlib
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - pandas
  - pytables  
  - dask
  - tabulate
  - tqdm
  # - pytorch:pytorch=2.5.1
  # - pytorch:torchvision=0.20.1
  - nvidia:pytorch-cuda=11.8
  - datasets
  - transformers
  - huggingface_hub
  - conda-forge::faiss-gpu
  - cython
  - conda-forge::wandb
  - conda-forge::omegaconf
  - statsmodels
  - natsort
  - seaborn
  - torchmetrics
  - pip
  - pip:
    - libmr
    - git+https://github.com/felixsh/nc-toolbox
    - git+https://github.com/felixsh/OpenOOD
